# Configuration of the crawler

config_name: YFCC100M_0

crawl_number: 200000 #number of images to crawl

crawl_order: seq # can use seq, rand, ..

use_mp: True # switch for whether use multiprocessing
mp_thread: 128


Download_image: true

Download_video: false


dataset_name_prefix: ../link/yfcc100m_dataset

video_save_folder: ../videos/

image_save_folder: ../images/

text_save_folder: ../des/

crawl_numbers: # id list of url link file, range 0-9, you can specify multiple link files here
  - 0

