# Configuration of the crawler

config_name: YFCC100M_0_VIDEO

crawl_number: 2000 #number of images to crawl

crawl_order: seq # can use seq, rand, ..

use_mp: True # switch for whether use multiprocessing
mp_thread: 32

dataset_name_prefix: ../link/yfcc_video_dataset

video_save_folder: ../videos/

image_save_folder: ../images/

text_save_folder: ../des/

crawl_numbers: # id list of url link file, range 0-9, you can specify multiple link files here
  - 0
